name: testipv6

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: IPv6Question
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - id: test
        run: |
          ip a l
          ip -6 route
          curl -6 https://google.com
